### ISSUE TITLE
load-samples recipe does not display any people at all: friends nor enemies

### ISSUE THREAD

**Issue by chrismurrph** [untangled-web/untangled-cookbook#12]
If you look at om/props being passed into Root:
ROOT: {:ui/react-key "58b00338-dd52-441c-8b72-83a48aa61c09", :enemies {}, :friends {}}

**Comment by awkay** [comment]
Weird...had a normalization problem, but it had worked for me. I guess I had not compiled it from scratch, and the REPL-based env I'd gotten into was working for a bad reason. Anyway, should work now. Please try it and let me know (be sure to clean if you're just going to pull)
